apiVersion: v1
kind: Secret
metadata:
  name: hobbies-secret
  namespace: hobbies-app
type: Opaque
stringData:
  # UPDATE THESE WITH YOUR REAL VALUES
  DB_PASSWORD: postgres
  JWT_SECRET: secretly123
  MAIL_PASSWORD: yaic bles epwb uasq
#  CLOUDINARY_API_SECRET: *****
#  CLOUDINARY_API_KEY: ******